// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDXC9BBVnV52o2TRHCvx7UNckX0kvS9k',
    appId: '1:635485236653:web:b144c7b679c16beba50524',
    messagingSenderId: '635485236653',
    projectId: 'imset-club-app',
    authDomain: 'imset-club-app.firebaseapp.com',
    storageBucket: 'imset-club-app.appspot.com',
    measurementId: 'G-9PY9H1G96E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLOJ8cA_ElkXTIFhAfK9ui-OHQFiFt1g',
    appId: '1:635485236653:android:87b076497b1415d9a50524',
    messagingSenderId: '635485236653',
    projectId: 'imset-club-app',
    storageBucket: 'imset-club-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXooOThQCCt_nZvcCiA7IuZIglMZId3tM',
    appId: '1:635485236653:ios:f41d154ce61b32dfa50524',
    messagingSenderId: '635485236653',
    projectId: 'imset-club-app',
    storageBucket: 'imset-club-app.appspot.com',
    iosBundleId: 'com.example.imsetClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXooOThQCCt_nZvcCiA7IuZIglMZId3tM',
    appId: '1:635485236653:ios:f41d154ce61b32dfa50524',
    messagingSenderId: '635485236653',
    projectId: 'imset-club-app',
    storageBucket: 'imset-club-app.appspot.com',
    iosBundleId: 'com.example.imsetClubApp',
  );
}
